### ISSUE TITLE
update to electron Fall17 VIDs V2

### ISSUE THREAD

**Issue by jalimena** [OSU-CMS/OSUT3Analysis#87] opened 2018-11-27 13:34 UTC
When we are ready to re-intuplize, we should update to the Fall17 V2 version of the electron VID. See https://github.com/OSU-CMS/OSUT3Analysis/pull/86

Basically, the "False" needs to be removed, and the updated compiling procedure needs to be implemented for CMSSW_9_4_9 and greater.

**Comment by bpf6qc** [comment] 2019-01-07 13:38
The VID implementation should be checked as well given changes in:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaMiniAODV2#2017_MiniAOD_V2

Also:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaMiniAODV2#Accessing_ID_result
is potentially important because the ValueMap associating electrons to VID values was very difficult to reproduce in multiple electron collections, this may make things much easier. (e.g. this here is a note to myself for when I look at doing this)

**Comment by jalimena** [comment] 2019-03-07 10:47
see also #113

**Comment by jalimena** [comment] 2019-03-07 16:45
ok so we can close this issue now, right? given #112  and #113 ?

**Comment by bpf6qc** [comment] 2019-03-07 17:29
@jalimena This issue is somewhat (?) still relevant I suppose, that users need to know this flag exists to control V2 IDs in 94X. But #112 and #113 do have the decision that we'll keep things the way they are, so it's not exactly an "issue" in github parlance anymore. So I would be in favor of closing this.

**Comment by jalimena** [comment] 2019-03-07 19:43
Yeah, I think it is no longer an issue we need to take care of, but rather an option we can do now. So I'm going to close this issue, and put a note about this option of using V2 in 94X on our analysis recipe twiki. I suggest you do the same.

**Closed** 2019-03-07 19:43 UTC
